name: Generate Documentation

# Trigger the workflow on push events for the master branch
on:  
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up Python build environment
      - run: python3 -m pip install --upgrade wheel
      - run: python3 -m pip install --upgrade setuptools
      - run: python3 -m pip install --upgrade pip

      # Install pdoc
      - run: python3 -m pip install pdoc3

      # Verify python packages installed properly
      - run: python3 -m pip list

      # Add python packages directory to PATH
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Check-out repository
      - uses: actions/checkout@v2
      - run: ls
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m pip install matplotlib

      # Generate documentation for each package
      - run: pdoc --html -o docs -f voxelfuse
      - run: pdoc --html -o docs -f voxelfuse_examples

      # Create a pull request for updated documentation
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update documentation
          branch: documentation-updates
          delete-branch: true
          title: 'Update documentation'
          body: |
            Generate updated package documentation

            - Documentation generated using [pdoc][1]
            - Pull request auto-generated by [create-pull-request][2]

            [1]: https://pdoc3.github.io/pdoc/
            [2]: https://github.com/peter-evans/create-pull-request
          labels: documentation
          
